### ISSUE TITLE
invinite loop by s-net(R) messages which cause a s-net device reset

### ISSUE THREAD

**Issue by Tonacatecuhtli** [Strunzdesign/hdlc-tools#2]
if you send a s-net(R) message which causes a s-net device reset the hdlcd starts an invinite loop of this message which causes a s-net device reset and so on.
![invinite destroy message loop](https://cloud.githubusercontent.com/assets/3892450/20489367/a655521e-b00a-11e6-8eb9-692b56ed5c96.PNG)

**Comment by Strunzdesign** [comment]
This is a bug of the s-net software of the tag, not of the HDLCd itself. If such a message triggers a reset of the s-net tag, and the tag is unable to send the respective S-RR frame, the HDLCd will continue to retransmit that frame forever. We have to fix the s-net software, I know where to look at :-)

Thanks, I'm closing this now...
